name: dockhand
services:
  dockhand:
    image: fnsys/dockhand:latest
    container_name: dockhand
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/docker/dockhand/data:/app/data
      - /opt/docker:/opt/docker
    environment:
      - HOST_DATA_DIR=/opt/docker
    networks:
      lan:
        ipv4_address: ${DOCKHAND_PRIVATE_IP}
    restart: unless-stopped

networks:
  lan:
    external: true