name: tdarr-server
services:
  tdarr:
    image: ghcr.io/haveagitgat/tdarr:latest
    container_name: tdarr-server
    volumes:
      - /opt/docker/tdarr/server:/app/server
      - /opt/docker/tdarr/configs:/app/configs
      - /opt/docker/tdarr/logs:/app/logs
      - /mnt/fx_media:/media
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
      - serverIP=${TDARR_SERVER_PRIVATE_IP}
      - serverPort=8266
      - webUIPort=8265
    networks:
      lan:
        ipv4_address: ${TDARR_SERVER_PRIVATE_IP}
    restart: unless-stopped

networks:
  lan:
    external: true